name: Build and Deploy Storybook

on:
  push:
    branches:
      - main  

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install dependencies
        run: npm ci

      - name: Build page
        run: npm run build:storybook

      - name: Deploy page
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: storybook-page
          folder: storybook-static